### ISSUE TITLE
Some questions about inference

### ISSUE THREAD

**Issue by ran894694447** [Tianfu18/diff-feats-pose#2]
Thanks for your great work! I would like to ask if this model requires the object's mask during inference? What is the inference speed?Looking forward to your early reply!

**Comment by Tianfu18** [comment]
Thank you for your attention to our work. We apologize for the delayed response. During inference, the object's mask is required, which is crucial for performance. As for inference speed, in our simple tests, on an A6000 GPU, the speed for the feature extraction part is about 10 frames per second.
