### ISSUE TITLE
replace stable-diffusion-1-5 model

### ISSUE THREAD

**Issue by qwerdzh** [Tianfu18/diff-feats-pose#3]
I changed stable-diffusion-1-5 from config_run to stable-diffusion-3-medium-diffusers,but there is a mistake here:
Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'vae', 'unet', 'image_encoder', 'text_encoder', 'feature_extractor', 'tokenizer', 'safety_checker', 'scheduler'}, but only {'vae', 'scheduler', 'tokenizer', 'text_encoder'} were passed.
How should it be solved?

**Comment by Tianfu18** [comment]
Our code currently does not support SD-V3. Please carefully check the network structure of both SD-V3 and SD-V1-5.
