### ISSUE TITLE
data.render_templates

### ISSUE THREAD

**Issue by acmff22** [Tianfu18/diff-feats-pose#4]
Thanks for your great work! I have problems in rendering templates. I follow the instructions of Data Preparation of README, but it reports : raise Exception("There are more object colors than there are objects"). 
<img width="724" alt="bcf9ebddc8cf773faad10f38f9d363c" src="https://github.com/user-attachments/assets/50642ada-fe34-48a2-92e8-9c04e40aa514">
Can you provide the templates images you use?
Looking forward to your early reply!

**Comment by Tianfu18** [comment]
We'll be uploading it soon.

**Comment by Tianfu18** [comment]
We have uploaded to this [link](https://drive.google.com/drive/folders/1CVyW7IDAZ0uGZSJIoN3ARRyP_wY2Ntk9?usp=sharing).
