### ISSUE TITLE
OLMresults

### ISSUE THREAD

**Issue by qwerdzh** [Tianfu18/diff-feats-pose#5]
On OLM data set，The result of training  and then testing is quite different from the result of the given pretrained test.

**Comment by Tianfu18** [comment]
your results?

**Comment by qwerdzh** [comment]
ye，I followed the code provided to reproduce and the results on the OLMdataset were very different from those in the paper。For example unseen_occ_acc：

pretrained_split2
{'seen_err': 4.020338509585563, 'seen_acc': 0.993883792048929, 'seen_occ_err': 9.4861058260868, 'seen_occ_acc': 0.8659242761692652, 'unseen_err': 2.491533233652202, 'unseen_acc': 0.9948707427164555, 'unseen_occ_err': 10.088256396094332, 'unseen_occ_acc': 0.8020767111676205}


ours
{'seen_err': 3.894989475453137, 'seen_acc': 0.9938837920489294, 'seen_occ_err': 11.710244415221577, 'seen_occ_acc': 0.8149220489977737, 'unseen_err': 3.3169533221516776, 'unseen_acc': 0.9725071809601985, 'unseen_occ_err': 13.278622619779107, 'unseen_occ_acc': 0.6916719643992372}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tianfu18/diff-feats-pose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tianfu18/diff-feats-pose] OLMresults (Issue #5)





 
your results?

**Comment by Tianfu18** [comment]
The results are as expected, with the instability on the O-LM dataset caused by randomness. Simply train multiple times and select the right checkpoint to reproduce the results. Often, the best checkpoint is found in the first few epochs, not necessarily the last one.

**Comment by qwerdzh** [comment]
Thank you very much for your answer.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tianfu18/diff-feats-pose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tianfu18/diff-feats-pose] OLMresults (Issue #5)





 
The results are as expected, with the instability on the O-LM dataset caused by randomness. Simply train multiple times and select the right checkpoint to reproduce the results. Often, the best checkpoint is found in the first few epochs, not necessarily the last one.
