### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hy66688** [Tianfu18/diff-feats-pose#6]
Hello, may I ask if the dataset is being prepared
├── LINEMOD.json # query-template pairwise for LINEMOD
├── occlusionLINEMOD.json # query-template pairwise for Occlusion-LINEMOD
├── tless_train.json # query-template pairwise for training split of T-LESS
├── tless_test.json # query-template pairwise for testing split of T-LESS
└── crop_image512 # pre-cropped images for LINEMOD
How did you get these? I couldn't find the Jason file. Is it convenient for the author to send them to me?

**Comment by Tianfu18** [comment]
Please follow step 5 of data preparation.
